/**
 * Auto-Memory Export Module
 *
 * Exports high-importance observations to Claude Code's auto-memory
 * topic files (~/.claude/projects/<path>/memory/).
 *
 * Writes to a dedicated topic file (context-manager-activity.md),
 * never touches MEMORY.md.
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { convertPathToDashed } from '../utils/transcript.js';
import type { Observation, ContextStorage } from '../storage/interface.js';

const TOPIC_FILE = 'context-manager-activity.md';
const DEFAULT_MAX_LINES = 150;

/**
 * Resolve the auto-memory directory for a project.
 * Returns ~/.claude/projects/{dashed-path}/memory/
 */
export function resolveMemoryDir(projectPath: string): string {
  const dashedPath = convertPathToDashed(projectPath);
  return join(homedir(), '.claude', 'projects', dashedPath, 'memory');
}

/**
 * Format high-importance observations as dated markdown for the topic file.
 * Groups by session, shows action verb + file + detail.
 */
export function formatObservationsForMemory(
  observations: Observation[]
): string {
  if (observations.length === 0) return '';

  // Group by date then session
  const byDate = new Map<string, Map<string, Observation[]>>();

  for (const obs of observations) {
    const date = obs.created_at.split('T')[0] ?? 'unknown'; // YYYY-MM-DD
    if (!byDate.has(date)) byDate.set(date, new Map());
    const dateGroup = byDate.get(date)!;
    if (!dateGroup.has(obs.session_id)) dateGroup.set(obs.session_id, []);
    dateGroup.get(obs.session_id)!.push(obs);
  }

  const lines: string[] = [];

  for (const [date, sessions] of byDate) {
    lines.push(`## ${date}`);
    lines.push('');

    for (const [sessionId, sessionObs] of sessions) {
      const shortId = sessionId.substring(0, 8);
      const first = sessionObs[0]!;
      const last = sessionObs[sessionObs.length - 1]!;
      const startTime = first.created_at.split('T')[1]?.substring(0, 5) ?? '';
      const endTime = last.created_at.split('T')[1]?.substring(0, 5) ?? '';

      lines.push(`### Session ${shortId} (${startTime} - ${endTime})`);

      for (const obs of sessionObs) {
        lines.push(`- ${formatObservationLine(obs)}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Format a single observation as a concise markdown line.
 */
function formatObservationLine(obs: Observation): string {
  const file = obs.files_touched[0] || '';
  const shortFile = file ? file.split('/').slice(-2).join('/') : '';

  // Map tool names to action verbs
  switch (obs.tool_name) {
    case 'Edit':
      return `**Edited** ${shortFile}${extractDetail(obs)}`;
    case 'Write':
      return `**Created** ${shortFile}${extractDetail(obs)}`;
    case 'Bash': {
      if (obs.summary.includes('git commit')) {
        const msg = obs.summary.match(/commit -m ["'](.+?)["']/)?.[1]
          || obs.summary.match(/"([^"]+)"/)?.[1]
          || '';
        return `**Git commit** — "${msg.substring(0, 80)}"`;
      }
      if (obs.summary.includes('git push')) return `**Git push** — ${obs.summary.substring(0, 80)}`;
      return `**Ran** ${obs.summary.substring(0, 80)}`;
    }
    case 'Read':
      return `**Read** ${shortFile}`;
    default:
      return `**${obs.tool_name}** ${obs.summary.substring(0, 80)}`;
  }
}

/**
 * Extract a brief detail suffix from an observation's summary.
 */
function extractDetail(obs: Observation): string {
  // Try to extract a meaningful suffix from the summary
  const summary = obs.summary;
  const dashIndex = summary.indexOf(' — ');
  if (dashIndex > 0) {
    return ` — ${summary.substring(dashIndex + 3, dashIndex + 83)}`;
  }
  const colonIndex = summary.indexOf(': ');
  if (colonIndex > 0 && colonIndex < 60) {
    return ` — ${summary.substring(colonIndex + 2, colonIndex + 82)}`;
  }
  return '';
}

/**
 * Write activity content to the topic file, trimming oldest entries if over limit.
 * Preserves the file header, appends new content, trims from the top of the body.
 */
export function writeActivityToMemory(
  projectPath: string,
  newContent: string,
  maxLines: number = DEFAULT_MAX_LINES
): { filePath: string; linesWritten: number } {
  const memoryDir = resolveMemoryDir(projectPath);
  mkdirSync(memoryDir, { recursive: true });

  const filePath = join(memoryDir, TOPIC_FILE);

  // Header for the topic file
  const header = [
    '# Project Activity Log',
    '',
    `> Auto-generated by context-manager. Updated ${new Date().toISOString()}.`,
    '> Use /ctx-search <query> for full history search.',
    '',
  ].join('\n');

  let existingBody = '';
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, 'utf-8');
    // Strip existing header (everything before first ## heading)
    const bodyMatch = existing.match(/^(## .+)/m);
    if (bodyMatch?.index !== undefined) {
      existingBody = existing.substring(bodyMatch.index);
    }
  }

  // Combine existing body + new content
  const fullBody = existingBody
    ? existingBody.trimEnd() + '\n\n' + newContent.trimEnd()
    : newContent.trimEnd();

  // Trim oldest entries if over line limit
  const bodyLines = fullBody.split('\n');
  const trimmedBody = bodyLines.length > maxLines
    ? bodyLines.slice(bodyLines.length - maxLines).join('\n')
    : fullBody;

  const finalContent = header + trimmedBody + '\n';
  writeFileSync(filePath, finalContent);

  return { filePath, linesWritten: trimmedBody.split('\n').length };
}

/**
 * Full export pipeline: query unexported high-importance observations,
 * format them, write to auto-memory topic file, and mark as exported.
 */
export async function exportToAutoMemory(
  storage: ContextStorage,
  projectPath: string,
  sessionId?: string
): Promise<{ exported: number; filePath: string | null }> {
  const observations = await storage.getUnexportedHighImportance(
    projectPath,
    sessionId
  );

  if (observations.length === 0) {
    return { exported: 0, filePath: null };
  }

  const formatted = formatObservationsForMemory(observations);
  const { filePath } = writeActivityToMemory(projectPath, formatted);

  // Mark as exported
  const ids = observations
    .map(o => o.id)
    .filter((id): id is number => id !== undefined);
  if (ids.length > 0) {
    await storage.markExported(ids);
  }

  return { exported: observations.length, filePath };
}
